name: Conventional Commits Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitizen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Check commits
        uses: commitizen-tools/commitizen-action@0.27.1 # 338bbd8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_only: true
